apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ghost
          image: ghost:5.115.1
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: mysql
            - name: database__connection__user
              value: ghost
            - name: database__connection__password
              value: ghostpassword
            - name: database__connection__database
              value: ghostdb
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: ghost-storage
              mountPath: /var/lib/ghost/content
              readOnly: false
          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: ghost-sa
      automountServiceAccountToken: false
      volumes:
        - name: ghost-storage
          persistentVolumeClaim:
            claimName: ghost-pvc
